name: automation pipeline

permissions:
  contents: write

on: 
  push:
  pull_request:

jobs: 
  tests: 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps: 
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:  
          python-version: "3.12"

      - name: Install dependencies
        run:  |  
          pip install pytest robotframework pytest robotframework-seleniumlibrary webdriver-manager

      - name: Install Chrome
        run:  | 
          sudo apt update
          sudo apt install -y chromium-browser  

      - name: Run pytest
        id:   pytest_steps
        continue-on-error: true
        env:
          CF_TEST_SECRET: ${{secrets.CF_TEST_SECRET}}
        run: |
            pytest python/testing/

      - name: Run robot tests
        if: always()
        env:
          CF_TEST_SECRET: ${{secrets.CF_TEST_SECRET}}
        run:  |
          robot -d test-results -v HEADLESS:True -v CF_TEST_SECRET:$CF_TEST_SECRET python/robot/
      
      - name: Prepare Report
        if: always()
        run: |
          mkdir -p docs
          if [ -f test-results/report.html ]; then
            cp test-results/report.html docs/index.html
          else
            echo "<h1>No report generated</h1>" > docs/index.html
          fi

      - name: commit report to repo 
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/
          git diff --staged --quiet || git commit -m "Update report"
          git push 


